//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class playerdbEntities : DbContext
    {
        public playerdbEntities()
            : base("name=playerdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<album> albums { get; set; }
        public virtual DbSet<artist> artists { get; set; }
        public virtual DbSet<song> songs { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<song_view> song_view { get; set; }
    }
}
