//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace server
{
    using System;
    using System.Collections.Generic;
    
    public partial class song_view
    {
        public int song_id { get; set; }
        public string song_name { get; set; }
        public string artist_name { get; set; }
        public string album_name { get; set; }
        public byte[] album_image { get; set; }
        public long file_length { get; set; }
    }
}
