//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace server
{
    using System;
    using System.Collections.Generic;
    
    public partial class song
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> artist_id { get; set; }
        public Nullable<int> album_id { get; set; }
        public byte[] file { get; set; }
        public long file_length { get; set; }
        public byte[] image { get; set; }
    
        public virtual album album { get; set; }
        public virtual artist artist { get; set; }
    }
}
